import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Lily_Script_One,
  Flow_Circular,
  Bricolage_Grotesque,
  Figtree,
} from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const lilyScriptOne = Lily_Script_One({
  weight: '400',
  variable: '--font-lily-script',
  subsets: ['latin'],
});

const flowCircular = Flow_Circular({
  weight: '400',
  variable: '--font-flow-circular',
  subsets: ['latin'],
});

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bricolage',
  // You can specify weights if needed, for example:
  // weights: [400, 500, 600, 700],
});

const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-figtree',
});

export const metadata: Metadata = {
  title: 'Toys To Stories!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lilyScriptOne.variable} ${flowCircular.variable} ${bricolageGrotesque.variable} ${figtree.variable} flex flex-col antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
