import type { Metadata } from 'next';
import { Geist, Geist_Mono, Lily_Script_One, Flow_Circular } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const lilyScriptOne = Lily_Script_One({
  weight: '400',
  variable: '--font-lily-script',
  subsets: ['latin'],
});

const flowCircular = Flow_Circular({
  weight: '400',
  variable: '--font-flow-circular',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Toys To Stories!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${lilyScriptOne.variable} ${flowCircular.variable} antialiased flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
